---
title: MSTech
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ahtisam.bashir@apexure.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/mstech"
url: http://mstech.siteleaf.net
footer-contact-number: "(202) 9892-40944"
brand-name: MSTech Solutions
footer-street-address: 23 Sector Main Street D,
footer-city: Manhattan, VA 20160,
footer-country: USA
list-nav-footer:
- Home
- About Us
- Contact us
- Blog
button-heading: Contact us
github_username: AhtisamBashir6
theme: minima
plugins:
- jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
